services:
  nginx:
    image: nginx:alpine
    container_name: procedure_nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot:/app/certbot:ro
      - ./certbot/letsencrypt:/etc/letsencrypt:ro
    networks:
      - procedure_network
    depends_on:
      - api
      - frontend
    restart: unless-stopped

networks:
  procedure_network:
    external: true
